import {
  LeadFull,
  LeadTemperature,
  LeadSource,
  PropertyType,
  OperationType,
  PropertyInterest,
} from "@/types/leads";

const mock_properties: PropertyInterest[] = [
  {
    id: "prop-1",
    code: "AP14150_SKY",
    address: "Rua Aimberê, 206",
    neighborhood: "Perdizes",
    city: "São Paulo",
    state: "SP",
    property_type: PropertyType.APARTMENT,
    operation_type: OperationType.SALE,
    bedrooms: 3,
    bathrooms: 2,
    area_sqm: 120,
    price: 850000,
    portal_url: "https://www.zapimoveis.com.br/imovel/ap14150",
    image_url: "/images/properties/ap1.jpg",
  },
  {
    id: "prop-2",
    code: "CA2891_VR",
    address: "Rua dos Pinheiros, 1500",
    neighborhood: "Pinheiros",
    city: "São Paulo",
    state: "SP",
    property_type: PropertyType.HOUSE,
    operation_type: OperationType.SALE,
    bedrooms: 4,
    bathrooms: 3,
    area_sqm: 250,
    price: 1800000,
    portal_url: "https://www.vivareal.com.br/imovel/ca2891",
  },
  {
    id: "prop-3",
    code: "AP8872_OLX",
    address: "Av. Ibirapuera, 2800",
    neighborhood: "Moema",
    city: "São Paulo",
    state: "SP",
    property_type: PropertyType.APARTMENT,
    operation_type: OperationType.RENT,
    bedrooms: 2,
    bathrooms: 1,
    area_sqm: 75,
    price: 4500,
  },
  {
    id: "prop-4",
    code: "COB1234_ZAP",
    address: "Rua Oscar Freire, 500",
    neighborhood: "Jardins",
    city: "São Paulo",
    state: "SP",
    property_type: PropertyType.PENTHOUSE,
    operation_type: OperationType.SALE,
    bedrooms: 4,
    bathrooms: 4,
    area_sqm: 350,
    price: 4500000,
  },
  {
    id: "prop-5",
    code: "ST5567_VR",
    address: "Rua Augusta, 1200",
    neighborhood: "Consolação",
    city: "São Paulo",
    state: "SP",
    property_type: PropertyType.STUDIO,
    operation_type: OperationType.RENT,
    bedrooms: 1,
    bathrooms: 1,
    area_sqm: 35,
    price: 2800,
  },
];

function hours_ago(hours: number): Date {
  return new Date(Date.now() - hours * 60 * 60 * 1000);
}

export const mock_leads: LeadFull[] = [
  {
    id: "lead-1",
    name: "João Silva",
    phone: "(11) 99999-1234",
    email: "joao.silva@gmail.com",
    status: "NEW",
    temperature: LeadTemperature.HOT,
    source: LeadSource.ZAP_IMOVEIS,
    source_email_subject: "Venda - Consulta para o imóvel em Rua Aimberê 206",
    notes: null,
    seller_id: "seller-1",
    seller_name: "Carlos Vendedor",
    area_id: "area-1",
    company_id: "company-1",
    property_interest: mock_properties[0],
    last_message: "Olá, gostaria de agendar uma visita para este apartamento. Tenho disponibilidade neste sábado.",
    last_message_at: hours_ago(2),
    last_contact_at: hours_ago(2),
    hours_without_response: 2,
    message_count: 3,
    created_at: hours_ago(24),
    updated_at: hours_ago(2),
  },
  {
    id: "lead-2",
    name: "Maria Santos",
    phone: "(11) 98888-5678",
    email: "maria.santos@hotmail.com",
    status: "QUALIFIED",
    temperature: LeadTemperature.HOT,
    source: LeadSource.VIVA_REAL,
    notes: "Interessada em financiamento",
    seller_id: "seller-1",
    seller_name: "Carlos Vendedor",
    area_id: "area-1",
    company_id: "company-1",
    property_interest: mock_properties[1],
    last_message: "Vocês trabalham com financiamento? Tenho 30% de entrada.",
    last_message_at: hours_ago(1),
    last_contact_at: hours_ago(1),
    hours_without_response: 1,
    message_count: 5,
    created_at: hours_ago(48),
    updated_at: hours_ago(1),
  },
  {
    id: "lead-3",
    name: "Pedro Costa",
    phone: "(11) 97777-9012",
    email: "pedro.costa@email.com",
    status: "CALLBACK",
    temperature: LeadTemperature.WARM,
    source: LeadSource.OLX,
    notes: "Retornar segunda-feira",
    seller_id: "seller-1",
    seller_name: "Carlos Vendedor",
    area_id: "area-1",
    company_id: "company-1",
    property_interest: mock_properties[2],
    last_message: "Vou pensar e retorno segunda-feira",
    last_message_at: hours_ago(24),
    last_contact_at: hours_ago(24),
    hours_without_response: 0,
    message_count: 8,
    created_at: hours_ago(72),
    updated_at: hours_ago(24),
  },
  {
    id: "lead-4",
    name: "Ana Oliveira",
    phone: "(11) 96666-3456",
    email: "ana.oliveira@gmail.com",
    status: "PROPOSAL",
    temperature: LeadTemperature.HOT,
    source: LeadSource.ZAP_IMOVEIS,
    notes: "Proposta de R$ 4.200.000 enviada",
    seller_id: "seller-2",
    seller_name: "Fernanda Silva",
    area_id: "area-1",
    company_id: "company-1",
    property_interest: mock_properties[3],
    last_message: "Proposta recebida. Vou analisar com meu advogado.",
    last_message_at: hours_ago(4),
    last_contact_at: hours_ago(4),
    hours_without_response: 0,
    message_count: 15,
    created_at: hours_ago(168),
    updated_at: hours_ago(4),
  },
  {
    id: "lead-5",
    name: "Lucas Mendes",
    phone: "(11) 95555-7890",
    email: "lucas.mendes@empresa.com.br",
    status: "NEW",
    temperature: LeadTemperature.COOLING,
    source: LeadSource.VIVA_REAL,
    notes: null,
    seller_id: "seller-1",
    seller_name: "Carlos Vendedor",
    area_id: "area-1",
    company_id: "company-1",
    property_interest: mock_properties[4],
    last_message: "Quanto é o condomínio?",
    last_message_at: hours_ago(72),
    last_contact_at: hours_ago(72),
    hours_without_response: 72,
    message_count: 2,
    created_at: hours_ago(96),
    updated_at: hours_ago(72),
  },
  {
    id: "lead-6",
    name: "Carla Souza",
    phone: "(11) 94444-2345",
    email: null,
    status: "NEW",
    temperature: LeadTemperature.WARM,
    source: LeadSource.WHATSAPP,
    notes: null,
    seller_id: "seller-2",
    seller_name: "Fernanda Silva",
    area_id: "area-1",
    company_id: "company-1",
    property_interest: mock_properties[0],
    last_message: "Vi o apartamento no ZAP. Ainda está disponível?",
    last_message_at: hours_ago(6),
    last_contact_at: hours_ago(6),
    hours_without_response: 6,
    message_count: 1,
    created_at: hours_ago(6),
    updated_at: hours_ago(6),
  },
  {
    id: "lead-7",
    name: "Roberto Lima",
    phone: "(11) 93333-6789",
    email: "roberto.lima@outlook.com",
    status: "QUALIFIED",
    temperature: LeadTemperature.COLD,
    source: LeadSource.FACEBOOK,
    notes: "Só vai comprar ano que vem",
    seller_id: "seller-1",
    seller_name: "Carlos Vendedor",
    area_id: "area-1",
    company_id: "company-1",
    property_interest: mock_properties[1],
    last_message: "Obrigado, mas só vou comprar ano que vem.",
    last_message_at: hours_ago(240),
    last_contact_at: hours_ago(240),
    hours_without_response: 0,
    message_count: 4,
    created_at: hours_ago(480),
    updated_at: hours_ago(240),
  },
  {
    id: "lead-8",
    name: "Fernanda Alves",
    phone: "(11) 92222-0123",
    email: "fernanda.alves@gmail.com",
    status: "NEW",
    temperature: LeadTemperature.HOT,
    source: LeadSource.IMOVEL_WEB,
    notes: null,
    seller_id: "seller-2",
    seller_name: "Fernanda Silva",
    area_id: "area-1",
    company_id: "company-1",
    property_interest: mock_properties[2],
    last_message: "Preciso para o mês que vem. Posso visitar amanhã?",
    last_message_at: hours_ago(0.5),
    last_contact_at: hours_ago(0.5),
    hours_without_response: 0.5,
    message_count: 2,
    created_at: hours_ago(3),
    updated_at: hours_ago(0.5),
  },
];

export function get_leads_by_seller(seller_id: string): LeadFull[] {
  return mock_leads.filter(l => l.seller_id === seller_id);
}

export function get_leads_by_company(company_id: string): LeadFull[] {
  return mock_leads.filter(l => l.company_id === company_id);
}

export function get_all_leads(): LeadFull[] {
  return mock_leads;
}

export function get_lead_by_id(lead_id: string): LeadFull | undefined {
  return mock_leads.find(l => l.id === lead_id);
}
